name: npm run build
on: [pull]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ vars.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_FOLDER: ${{ secrets.CLOUDINARY_FOLDER }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          npm-version: 9.6.7
      - run: npm install
      - run: npm run lint
      - run: npm run build
